server:
  port: 8001
spring:
  application:
    name: cloud-demo-user
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-zero?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  profiles:
    active: 8002


mybatis:
  type-aliases-package: com.yailjj.cloud.demo.user.domain    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mapper/*.xml                            # mapper映射文件
eureka:
  client: # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true     # 访问路径可以显示IP地址
#后面监控也会用到
info:
  app.name: cloud-demo
  company.name: www.yailjj.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
---
spring:
  profiles: 8001
server:
  port: 8001

---
spring:
  profiles: 8002
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-zero2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
server:
  port: 8002